server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:360595304/springcloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-config
      ####读取分支
      label: main # 新版本为main，老版本为master
  rabbitmq:
    addresses: 192.168.227.130
    username: admin
    password: 123456
    port: 5672

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


# rabbitmq暴露bus刷新的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
